title: Ensamblando código - Bitácora tecnológica
iconURL: assets/default-icon.png
theme: jekyll-theme-slate

# for a clean URL
permalink: :slug

social:
  linkedin: linkedin.com/in/rubén-rojo-vázquez-395641225
  github: rubenrojov

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 10034
google_analytics: G-HDGQWPHSD1
